spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD}}
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT:6379}
  jpa:
    show-sql: false
