spring:
  application:
    name: hwayoung-server
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
#      위에서 none에서 바꿈
    properties:
      hibernate:
        format_sql: true
  profiles:
    group:
      dev-create: dev,ddl-create
      dev-create-drop: dev,ddl-create-drop
      dev-update: dev,ddl-update
      dev-validate: dev,ddl-validate
      dev-none: dev,ddl-none
      prod-create: prod,ddl-create
      prod-create-drop: prod,ddl-create-drop
      prod-update: prod,ddl-update
      prod-validate: prod,ddl-validate
      prod-none: prod,ddl-none
jwt:
  secret: ${JWT_SECRET}
  expiration: 43200000